// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_ui_auth/firebase_ui_auth.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXbbSsDVH1eVE297nCyU9euFilYmJWH1U',
    appId: '1:553932496521:web:bec35d05cb23cd9beef058',
    messagingSenderId: '553932496521',
    projectId: 'culinect-social',
    authDomain: 'culinect-social.firebaseapp.com',
    databaseURL: 'https://culinect-social-default-rtdb.firebaseio.com',
    storageBucket: 'culinect-social.appspot.com',
    measurementId: 'G-RQ20V98BR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEyLE2_YTX8x6zPm7z0Vpbr_ETbcFUz9Y',
    appId: '1:553932496521:android:1ae9ade2d19bc0a9eef058',
    messagingSenderId: '553932496521',
    projectId: 'culinect-social',
    databaseURL: 'https://culinect-social-default-rtdb.firebaseio.com',
    storageBucket: 'culinect-social.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpEDs1cwNTkA_Sn8bs-hQ9dZNJMBSRofc',
    appId: '1:553932496521:ios:9a6468935f7ac375eef058',
    messagingSenderId: '553932496521',
    projectId: 'culinect-social',
    databaseURL: 'https://culinect-social-default-rtdb.firebaseio.com',
    storageBucket: 'culinect-social.appspot.com',
    iosClientId: '553932496521-qfnmge96pp5kfaosa75kgqnovn14buea.apps.googleusercontent.com',
    iosBundleId: 'com.culinect.culinect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpEDs1cwNTkA_Sn8bs-hQ9dZNJMBSRofc',
    appId: '1:553932496521:ios:810b5c3dd099dff8eef058',
    messagingSenderId: '553932496521',
    projectId: 'culinect-social',
    databaseURL: 'https://culinect-social-default-rtdb.firebaseio.com',
    storageBucket: 'culinect-social.appspot.com',
    iosClientId: '553932496521-odhg1euo3ktrsdl3bs5g0h3vmpt0si7n.apps.googleusercontent.com',
    iosBundleId: 'com.culinect.culinect.RunnerTests',
  );
}
final actionCodeSettings = ActionCodeSettings(
  url: 'https://flutterfire-e2e-tests.firebaseapp.com',
  handleCodeInApp: true,
  androidMinimumVersion: '1',
  androidPackageName: 'io.flutter.plugins.firebase_ui.firebase_ui_example',
  iOSBundleId: 'io.flutter.plugins.fireabaseUiExample',
);

final emailLinkProviderConfig = EmailLinkAuthProvider(
  actionCodeSettings: actionCodeSettings,
);